import dynamical_bifurcation_solutions_dynamical_problems_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace dynamical_bifurcation_solutions_dynamical_problems_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end dynamical_bifurcation_solutions_dynamical_problems_theorem_canonical_lane_mathlib
end HautevilleHouse
